name: BattleKits
main: com.lavacraftserver.Battlekits.BattleKits
version: 1.7 -DEV
author: np98765
authors: ['lol768', 'MapleFighter777']
softdepend: [Vault, TagAPI]
commands:
  battlekits:
    usage: /<command> [kit]
    description: Gives a kit
    aliases: [bk,kit]
  soup:
    usage: /soup
    description: Refills soup bowl in your hand
    aliases: [refill,stew]
  fillall:
    usage: /fillall
    description: Refills all soup in inventory
    aliases: [fullsoup]
